### ISSUE TITLE
SR in metric_use.py and metric_use_simple.py?

### ISSUE THREAD

**Issue by turian** [pranaymanocha/PerceptualAudio#11]
In metric_use.py and metric_use_simple.py I see the following:

* If it is an mp3, convert it to wav with SR 16000.
* If it is a wav, use scipy.io.wavfile to read it, which does not change the samplerate and just returns it, which the code ignores.

Is the desired behavior:
1) Those scripts should resample audio to SR 16000?
or
2) The README should suggest converting your audio to SR 16000?

**Comment by pranaymanocha** [comment]
Hi. Thanks for noticing this. We tried training models on a bunch of sampling rates (16k,22k). The training script currently resamples the rate to 16KHz, but the pretrained models all support **22050Hz**. If you look at the audio samples provided in the repo, those are all 22KHz. I'll make a note in the repo so that it's more clear.

**Comment by turian** [comment]
Thanks. The training rate was in the code, and then the paper / dataset said 48000 but some of the audio in the dataset zip in 44100. Some clarifications would be great!

**Comment by pranaymanocha** [comment]
Sorry for my late response. I have updated the README and training scripts to make the distance eval code sr invariant. That should be helpful! In short, the pre-trained models are all in 22050Hz, but you could use the JND dataset by resampling the file to any rate that you need for your task.
